services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@lbaw.com
      PGADMIN_DEFAULT_PASSWORD: secret

      # Disable user passwords. Only to be used in local single-user model.
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "4321:80"
    depends_on:
      - postgres

  app:
    image: php:8
    depends_on:
      - postgres
    command: /bin/sh -c 'while true; do sleep 3600; done'
    ports:
      - "8000:8000"
    volumes:
      - .:/app
